/**
 * Composition QA Skill.
 *
 * Reviews visual composition quality: image/text balance, focal points,
 * section rhythm, layout variation, and visual weight distribution.
 * Thinks like a visual director reviewing a magazine layout.
 */

import type { GenerationContext } from "../../src/contracts/types.js";
import { BaseSkill, type SkillResult } from "../../src/contracts/skill.js";

// ─────────────────────────────────────────────────────────────────────────────
//  PROMPT BLOCK
// ─────────────────────────────────────────────────────────────────────────────

export function buildCompositionQaBlock(): string {
  return `
━━ VISUAL COMPOSITION REVIEW ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Evaluate visual composition as a creative director reviewing a premium brand site.

IMAGE/TEXT BALANCE:
□ Hero section has strong visual balance: meaningful text column + rich visual column.
□ Text-heavy sections are broken up with visual elements (icons, illustrations, photos).
□ No section is more than 3 paragraphs of text without a visual element.
□ Images/illustrations are proportional to the text they accompany.

SECTION RHYTHM & VARIETY:
□ Not all sections use the same layout (avoid: 3-col cards, 3-col cards, 3-col cards).
□ Page includes at least 2 different section layout patterns (e.g., hero, 3-col, 2-col editorial, full-width CTA).
□ Section backgrounds alternate to create visual rhythm (light → tinted → light).
□ The page feels like it was designed with intent, not generated by formula.

FOCAL POINTS:
□ Each section has a clear focal point — the eye knows where to land first.
□ CTA buttons act as focal points and draw attention appropriately.
□ The hero headline is the dominant visual element above the fold.
□ Product/service visuals act as focal points in their sections.

VISUAL WEIGHT DISTRIBUTION:
□ The page is visually balanced — no half looks heavy while the other is empty.
□ Large decorative elements (hero illustration, background pattern) don't overwhelm content.
□ Color weight is distributed — the brand color appears throughout, not just at the top.
□ Images and text blocks have similar visual weight in two-column layouts.

CONTENT QUALITY:
□ Section headings are compelling and specific (not "Our Products" but "Lithium Battery Solutions").
□ Descriptions communicate value, not just describe features.
□ Stats/numbers (if present) are real and specific (not "0 clients" or "X years").
□ Vietnamese content is correctly rendered (no encoding issues, no Lorem Ipsum).

COMPOSITION FAILURE PATTERNS:
✗ Every section is a centered-heading + 3-column card grid — monotonous.
✗ Hero right column is empty or has a tiny illustration lost in whitespace.
✗ A "stats" or "about" section has zero visible numbers or imagery.
✗ The page looks like a template with swapped text, not a designed site.
✗ A section has no heading and no context — the user doesn't know what they're looking at.
`.trim();
}

// ─────────────────────────────────────────────────────────────────────────────
//  SKILL
// ─────────────────────────────────────────────────────────────────────────────

export interface CompositionQaOutput {
  criteriaBlock: string;
}

export class CompositionQaSkill extends BaseSkill<void, CompositionQaOutput> {
  readonly name = "qa/composition";
  readonly description = "Visual composition QA: image/text balance, section rhythm, focal points, layout variety";
  readonly version = "1.0.0";


  async execute(_input: void, _ctx: GenerationContext): Promise<SkillResult<CompositionQaOutput>> {
    const start = Date.now();
    this.logs = [];
    const criteriaBlock = buildCompositionQaBlock();
    return {
      success: true,
      data: { criteriaBlock },
      logs: this.logs,
      retries: 0,
      durationMs: Date.now() - start,
    };
  }
}

export const compositionQaSkill = new CompositionQaSkill();
