/**
 * PHPStan Static Analysis Skill.
 *
 * Runs PHPStan on generated PHP files to catch type errors, undefined
 * variables, unreachable code, and other static analysis issues.
 *
 * Generates a minimal PHPStan bootstrap file that defines ABSPATH and
 * WordPress stubs so analysis can run without a live WordPress install.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import type {
  GenerationContext,
  ValidationResult,
  ValidationError,
} from "../../src/contracts/types.js";
import { BaseSkill, type SkillResult } from "../../src/contracts/skill.js";
import { listFilesSafe } from "../../src/core/fs.js";
import { execSafeAsync, commandExists } from "../../src/core/exec.js";

// ─────────────────────────────────────────────────────────────────────────────
//  PHPSTAN BOOTSTRAP TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────

function generateBootstrap(ctx: GenerationContext): string {
  const slug = ctx.projectSlug;
  const prefix = ctx.phpPrefix;
  const isPlugin = ctx.analysis?.projectType === "wordpress_plugin";

  return `<?php
/**
 * PHPStan bootstrap for WordPress analysis.
 * Auto-generated by ai-agent-wordpress — do not edit manually.
 */

// Define WordPress constants
define( 'ABSPATH', __DIR__ . '/' );
define( 'WPINC', 'wp-includes' );
define( 'WP_CONTENT_DIR', __DIR__ . '/wp-content' );
define( 'WP_PLUGIN_DIR', __DIR__ . '/wp-content/plugins' );
define( 'TEMPLATEPATH', __DIR__ . '/' );
define( 'STYLESHEETPATH', __DIR__ . '/' );

${isPlugin ? `// Plugin constants
define( '${prefix.toUpperCase()}_VERSION', '1.0.0' );
define( '${prefix.toUpperCase()}_PLUGIN_DIR', __DIR__ . '/' );
define( '${prefix.toUpperCase()}_PLUGIN_URL', 'http://localhost/' );` : `// Theme constants  
define( '${prefix.toUpperCase()}_VERSION', '1.0.0' );`}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
//  PHPSTAN CONFIG TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────

function generateNeon(bootstrapPath: string, phpFiles: string[]): string {
  return `parameters:
  level: 5
  paths:
${phpFiles.map((f) => `    - ${f}`).join("\n")}
  bootstrapFiles:
    - ${bootstrapPath}
  ignoreErrors:
    - '#Call to an undefined function (add_action|add_filter|apply_filters|do_action|wp_enqueue_|get_template_part|get_header|get_footer|get_sidebar|register_nav_menus|add_theme_support|bloginfo|get_bloginfo|the_title|the_content|the_excerpt|the_post_thumbnail|have_posts|the_post|wp_reset_postdata|get_posts|WP_Query|wp_die|wp_redirect|wp_safe_redirect|esc_html|esc_url|esc_attr|sanitize_text_field|absint|wp_nonce_field|wp_verify_nonce|current_user_can|is_admin|is_user_logged_in|get_option|update_option|delete_option|add_option|WC|wc_).*#'
    - '#Access to an undefined property WP_#'
    - '#Call to an undefined method WP_#'
`;
}

// ─────────────────────────────────────────────────────────────────────────────
//  TYPES
// ─────────────────────────────────────────────────────────────────────────────

export interface PhpstanResult {
  available: boolean;
  violations: ValidationError[];
  rawOutput: string;
  level: number;
  filesAnalysed: number;
}

export interface PhpstanSkillInput {
  /** PHPStan level 0-9 (default: 5) */
  level?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  SKILL
// ─────────────────────────────────────────────────────────────────────────────

export class PhpstanSkill extends BaseSkill<PhpstanSkillInput, PhpstanResult> {
  readonly name = "validation/phpstan";
  readonly description = "Runs PHPStan static analysis on generated PHP files";
  readonly version = "1.0.0";

  validators = [
    (output: PhpstanResult): ValidationResult => {
      if (!output.available) {
        return {
          valid: true,
          errors: [],
          warnings: [{ file: "system", message: "PHPStan not available", severity: "warning" as const }],
        };
      }
      return {
        valid: output.violations.length === 0,
        errors: output.violations,
        warnings: [],
        score: Math.max(0, 100 - output.violations.length * 5),
      };
    },
  ];

  async execute(
    input: PhpstanSkillInput,
    ctx: GenerationContext,
  ): Promise<SkillResult<PhpstanResult>> {
    const start = Date.now();
    this.logs = [];

    const level = input.level ?? 5;

    // Check for PHPStan
    const phpstanPath = this.findPhpstan();
    if (!phpstanPath) {
      this.log("PHPStan not found — skipping (install via: composer global require phpstan/phpstan)");
      return this.buildResult(
        true,
        { available: false, violations: [], rawOutput: "", level, filesAnalysed: 0 },
        start,
        0,
        undefined,
        ["PHPStan not installed — static analysis skipped"],
      );
    }

    // Get PHP files
    const allFiles = await listFilesSafe(ctx.workspacePath);
    const phpFiles = allFiles.filter(
      (f) => f.endsWith(".php") && !f.includes(".router.php") && !f.includes("vendor/"),
    );

    if (phpFiles.length === 0) {
      return this.buildResult(true, { available: true, violations: [], rawOutput: "", level, filesAnalysed: 0 }, start);
    }

    // Create .agent-artifacts/ directory for temp files
    const artifactsDir = path.join(ctx.workspacePath, ".agent-artifacts");
    await fs.mkdir(artifactsDir, { recursive: true });

    // Generate bootstrap and neon config
    const bootstrapPath = path.join(artifactsDir, "phpstan-bootstrap.php");
    const neonPath = path.join(artifactsDir, "phpstan.neon");

    await fs.writeFile(bootstrapPath, generateBootstrap(ctx), "utf-8");
    await fs.writeFile(neonPath, generateNeon(bootstrapPath, phpFiles), "utf-8");

    this.log(`Running PHPStan level ${level} on ${phpFiles.length} file(s)…`);

    const result = await execSafeAsync(
      `"${phpstanPath}" analyse --configuration="${neonPath}" --level=${level} --no-progress --error-format=json`,
      ctx.workspacePath,
      120_000,
    );

    let violations: ValidationError[] = [];
    let rawOutput = result.stdout;

    try {
      const json = JSON.parse(result.stdout) as {
        files?: Record<string, { errors: Array<{ line: number; message: string }> }>;
        totals?: { errors: number };
      };

      if (json.files) {
        for (const [filePath, fileData] of Object.entries(json.files)) {
          for (const err of fileData.errors) {
            violations.push({
              file: path.relative(ctx.workspacePath, filePath),
              line: err.line,
              message: err.message,
              severity: "error",
            });
          }
        }
      }
    } catch {
      // Fall back to raw output parsing
      rawOutput = result.stdout + result.stderr;
    }

    this.log(`PHPStan: ${violations.length} issue(s) found`);

    return this.buildResult(
      violations.length === 0,
      { available: true, violations, rawOutput: rawOutput.slice(0, 3000), level, filesAnalysed: phpFiles.length },
      start,
    );
  }

  private findPhpstan(): string | null {
    const candidates = [
      "phpstan",
      "vendor/bin/phpstan",
      path.join(process.env.HOME ?? "", ".composer/vendor/bin/phpstan"),
    ];
    for (const c of candidates) {
      if (commandExists(c)) return c;
    }
    return null;
  }
}

export const phpstanSkill = new PhpstanSkill();
