/**
 * Generation prompts — used by the codeGenerator agent and theme/plugin skills.
 */

import { WORDPRESS_PRODUCTION_SYSTEM_PROMPT } from "./wordpress-system.js";
import type { GenerationContext } from "../contracts/types.js";

// ─────────────────────────────────────────────────────────────────────────────
//  THEME GENERATION PROMPT
// ─────────────────────────────────────────────────────────────────────────────

export function buildThemeBatchPrompt(
  ctx: GenerationContext,
  batchFiles: Array<{ filePath: string; description: string }>,
  batchIdx: number,
  totalBatches: number,
  alreadyGeneratedContext: string,
  cssVarsBlock: string,
  actualPrefix: string,
): string {
  const fileList = batchFiles
    .map((f) => `  - ${f.filePath}: ${f.description}`)
    .join("\n");

  return `[GENERATE_CODE]
${WORDPRESS_PRODUCTION_SYSTEM_PROMPT}

Generate production-ready WordPress theme files.

Project slug   : ${ctx.analysis?.projectName ?? "wordpress-theme"}
Project type   : wordpress_theme
Brand name     : ${ctx.analysis?.brandName ?? ctx.idea}
PHP prefix     : ${actualPrefix}_
Text domain    : ${ctx.analysis?.projectName ?? "wordpress-theme"}
User's idea    : "${ctx.idea}"
Target audience: ${ctx.analysis?.targetAudience ?? "general"}
Design tone    : ${ctx.analysis?.designDirection?.tone ?? "modern"}
Color palette  : ${ctx.analysis?.designDirection?.colorPalette ?? "neutral"}
${cssVarsBlock}
${alreadyGeneratedContext}

Generate ONLY these files (batch ${batchIdx + 1}/${totalBatches}):
${fileList}

Respond with a JSON array:
[
  { "filePath": "<exact path>", "content": "<full file content>" }
]

WORDPRESS THEME RULES:
- style.css must start with the WordPress theme header comment block (Theme Name, Version, etc.)
- functions.php must call add_theme_support() for title-tag, post-thumbnails, html5, custom-logo
- functions.php must register at least one nav menu location with register_nav_menus()
- functions.php MUST define a {prefix}_fallback_menu() function and pass it as fallback_cb to wp_nav_menu() — this function outputs a <ul> with a Home link and wp_list_pages(); absence causes an empty nav on fresh installs
- header.php must call wp_head() before </head> and wp_body_open() after <body>
- footer.php must call wp_footer() before </body>
- All template files must call get_header() and get_footer()
- comments.php MUST exist and call comments_template() integration: wp_list_comments() + comment_form(); its absence triggers a PHP deprecation on every post/page
- Use get_template_part() for reusable sections — never duplicate markup
- inc/theme-data.php is the SINGLE source of demo data; prefix every function with ${actualPrefix}_
- Data consumers (template-parts) must ONLY access keys returned by inc/theme-data.php functions
- No remote placeholder image URLs (loremflickr, picsum, placehold, etc.)
- Use inline SVG or CSS-generated placeholders for demo images
- Never use position: fixed on .site-header without compensating body padding-top

NAV / JS ALIGNMENT RULE (critical — prevents broken menus):
- wp_nav_menu() 'menu_class' value is the <ul> class; 'container' => false means NO extra wrapper
- All CSS selectors and JS querySelector() calls MUST match the EXACT class names generated by wp_nav_menu()
- Example: if wp_nav_menu sets menu_class='main-navigation__menu', then CSS must style '.main-navigation__menu', NOT '.site-header__menu'
- The mobile toggle button class in HTML (e.g. 'menu-toggle') must match the JS querySelector AND the CSS selector exactly — three-way match required
- Never define CSS for a class that no element in the HTML actually has

CSS COVERAGE RULE (critical):
- style.css must contain styles for ALL WordPress templates, not just front-page sections
- Required CSS blocks: site-header, front-page sections, single-post (with all BEM elements), archive-content, post-card, page-header, page-content, comments-area + comment-form, pagination (.nav-links), 404/no-results, AND responsive breakpoints for each
- Inner templates (single.php, archive.php, page.php) will be unstyled and broken if you omit their CSS

CSS RULES:
- Every var(--X) must be declared in :root
- Transitions only inside @media (prefers-reduced-motion: no-preference)
- Mobile-first breakpoints (min-width)
- No bare hex/rgb literals — always CSS custom properties

ACCESSIBILITY:
- <main id="main-content"> skip-link target
- <nav aria-label="Primary navigation">
- Every <img> has descriptive alt=""
- :hover effects must have :focus-visible equivalents

⚠️ SELF-CHECK before returning JSON:
1. Every var(--X) used in CSS exists in :root of style.css.
2. No transition: outside @media (prefers-reduced-motion).
3. Every function called in template-parts is defined in inc/theme-data.php with prefix ${actualPrefix}_.
4. functions.php requires inc/theme-data.php and inc/customizer.php.
5. No TODO, no "...", no placeholder text in any file.
6. Every CSS class matches its HTML counterpart exactly.
7. Every id anchor used by nav links exists in the markup.
8. No specs/iterable key accessed unless it is an array in inc/theme-data.php.
9. style.css contains .single-post styles (or equivalent BEM block for the single template).
10. style.css contains .archive-content / .post-card styles for the archive/blog template.
11. style.css contains .comments-area and .comment-form styles.
12. comments.php exists in the file list being generated or was already generated.
13. functions.php defines a {prefix}_fallback_menu() function.
14. Every CSS selector and JS querySelector() call matches the EXACT class names in the HTML templates (three-way HTML/CSS/JS consistency). The menu_class passed to wp_nav_menu() must have a matching CSS block — do not invent a different class in the stylesheet.
15. The mobile toggle button class in HTML matches both the CSS selector and the JS querySelector — if HTML says class="menu-toggle", CSS and JS must also use .menu-toggle.

Return ONLY the ${batchFiles.length} file(s) listed above`;
}

// ─────────────────────────────────────────────────────────────────────────────
//  PLUGIN GENERATION PROMPT
// ─────────────────────────────────────────────────────────────────────────────

export function buildPluginBatchPrompt(
  ctx: GenerationContext,
  batchFiles: Array<{ filePath: string; description: string }>,
  batchIdx: number,
  totalBatches: number,
  alreadyGeneratedContext: string,
  pluginMainFile: string,
): string {
  const fileList = batchFiles
    .map((f) => `  - ${f.filePath}: ${f.description}`)
    .join("\n");

  const phpPrefix = ctx.phpPrefix;

  return `[GENERATE_CODE]
${WORDPRESS_PRODUCTION_SYSTEM_PROMPT}

Generate production-ready WordPress plugin files.

Project slug   : ${ctx.analysis?.projectName ?? "wordpress-plugin"}
Project type   : wordpress_plugin
Brand name     : ${ctx.analysis?.brandName ?? ctx.idea}
PHP prefix     : ${phpPrefix}_
Text domain    : ${ctx.analysis?.projectName ?? "wordpress-plugin"}
Main file      : ${pluginMainFile}
User's idea    : "${ctx.idea}"
Full file list : ${ctx.spec?.fileStructure.map((f) => f.filePath).join(", ") ?? ""}

${alreadyGeneratedContext}

Generate ONLY these files (batch ${batchIdx + 1}/${totalBatches}):
${fileList}

Respond with a JSON array:
[
  { "filePath": "<exact path>", "content": "<full file content>" }
]

WORDPRESS PLUGIN RULES:
- Root bootstrap ${pluginMainFile} MUST contain a valid WordPress plugin header:
    /**
     * Plugin Name: ...
     * Plugin URI: ...
     * Description: ...
     * Version: 1.0.0
     * Author: ...
     * Text Domain: ${ctx.analysis?.projectName ?? "plugin"}
     * Domain Path: /languages
     */
- Register activation hook with register_activation_hook( __FILE__, array( '${phpPrefix}_Activator', 'activate' ) )
- Register deactivation hook with register_deactivation_hook()
- Uninstall.php must check: if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) { exit; }
- Use WPCS-compliant class filenames:  class-{slug}-admin.php, class-{slug}-public.php
- All constants prefixed: ${phpPrefix.toUpperCase()}_VERSION, ${phpPrefix.toUpperCase()}_PLUGIN_DIR
- Admin writes: sanitize input, verify nonce, check current_user_can() capability
- Enqueue assets via wp_enqueue_scripts / admin_enqueue_scripts hooks only
- All user-visible strings wrapped in __() / _e() with text domain "${ctx.analysis?.projectName}"
- Guard WooCommerce integrations with class_exists( 'WooCommerce' )
- readme.txt in WordPress.org format (plain text, NOT markdown)

SECURITY SELF-CHECK:
1. Every admin form has wp_nonce_field() and server-side wp_verify_nonce().
2. Every privileged action has current_user_can() check.
3. All $wpdb queries use $wpdb->prepare().
4. All output is escaped with esc_html(), esc_url(), esc_attr().
5. No eval(), no base64_decode(), no remote shells.

Return ONLY the ${batchFiles.length} file(s) listed above`;
}

// ─────────────────────────────────────────────────────────────────────────────
//  SPEC BUILDER PROMPT
// ─────────────────────────────────────────────────────────────────────────────

export function buildSpecPrompt(
  idea: string,
  analysis: string,
  projectType: string,
): string {
  const isTheme = projectType === "wordpress_theme";

  return `[BUILD_SPEC]
${WORDPRESS_PRODUCTION_SYSTEM_PROMPT}

Create a detailed project specification for a WordPress ${isTheme ? "theme" : "plugin"}.

USER IDEA: "${idea}"

ANALYSIS:
${analysis}

Return JSON matching this schema exactly:
{
  "projectType": "${projectType}",
  "architecture": "description of the architecture",
  "fileStructure": [
    { "filePath": "relative/path/file.php", "description": "what this file does" }
  ],
  "apiEndpoints": [],
  "buildScript": "",
  "testScript": "php -l *.php"
}

${isTheme ? THEME_FILE_STRUCTURE_GUIDE : PLUGIN_FILE_STRUCTURE_GUIDE}

RULES:
- fileStructure must include ALL files required for the project to work after installation
- Every filePath must be relative to the project root (no leading slash)
- Include inc/theme-data.php and inc/customizer.php for themes
- Include all class files under includes/, admin/, public/ for plugins
- Do NOT include binary files (png, jpg, gif, woff) — the agent handles those separately
- Minimum viable theme: style.css, functions.php, index.php, front-page.php, header.php, footer.php, inc/theme-data.php, inc/customizer.php
- Minimum viable plugin: {slug}.php, uninstall.php, readme.txt, includes/class-loader.php, includes/class-plugin.php, includes/class-activator.php, includes/class-deactivator.php`;
}

const THEME_FILE_STRUCTURE_GUIDE = `
REQUIRED THEME FILES (always include):
  style.css, functions.php, index.php, front-page.php, single.php,
  page.php, comments.php, header.php, footer.php, 404.php, archive.php,
  inc/theme-data.php, inc/customizer.php,
  assets/js/main.js, assets/css/ (component files)
  template-parts/ (section partials for front-page)

CRITICAL: style.css MUST include CSS for every template (front-page sections AND
inner-page templates: .single-post, .archive-content, .post-card, .page-header,
.page-content, .comments-area, .comment-form, .nav-links, .no-results).
Common mistake: generating CSS only for front-page hero/sections and leaving
single.php / archive.php / comments unstyled.`;

const PLUGIN_FILE_STRUCTURE_GUIDE = `
REQUIRED PLUGIN FILES (always include):
  {slug}.php (bootstrap), uninstall.php, readme.txt,
  includes/class-loader.php, includes/class-plugin.php,
  includes/class-activator.php, includes/class-deactivator.php,
  admin/class-{slug}-admin.php,
  public/class-{slug}-public.php`;

// ─────────────────────────────────────────────────────────────────────────────
//  IDEA ANALYSIS PROMPT
// ─────────────────────────────────────────────────────────────────────────────

export function buildAnalysisPrompt(idea: string): string {
  return `[ANALYZE_IDEA]
${WORDPRESS_PRODUCTION_SYSTEM_PROMPT}

Analyse this idea and return a structured JSON analysis.

USER IDEA: "${idea}"

Determine if this should be a WordPress theme or plugin:
- If it describes a website / store / landing page / portfolio → wordpress_theme
- If it describes a feature/tool that extends WordPress → wordpress_plugin

Return JSON matching this schema:
{
  "projectType": "wordpress_theme" | "wordpress_plugin",
  "projectName": "kebab-case-slug",
  "brandName": "Human Brand Name",
  "summary": "2-3 sentence summary",
  "targetAudience": "description of target users",
  "goals": ["goal1", "goal2"],
  "features": [
    {
      "name": "Feature Name",
      "description": "what it does",
      "priority": "high" | "medium" | "low",
      "acceptanceCriteria": ["criterion1"]
    }
  ],
  "userStories": [
    { "role": "visitor", "goal": "what they want to do", "rationale": "why" }
  ],
  "designDirection": {
    "tone": "modern/minimal/bold/warm/professional",
    "colorPalette": "description of colors",
    "typography": "font style",
    "inspiration": ["reference1"]
  },
  "nonFunctionalRequirements": {
    "performance": ["requirement"],
    "accessibility": ["WCAG 2.1 AA"],
    "seo": ["requirement"]
  },
  "contentRequirements": ["content type needed"],
  "techStack": {
    "frontend": ["HTML5", "CSS3", "Vanilla JS"],
    "backend": ["PHP 8.0+", "WordPress 6.0+"],
    "devtools": ["WP-CLI"]
  }
}`;
}
